# Generated by Django 5.0.2 on 2024-02-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processors',
            new_name='Product',
        ),
    ]
